services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d app" ]
      interval: 2s
      timeout: 3s
      retries: 10
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/app
      EXTERNAL_API_URL: https://api.randomdatatools.ru/
      INITIAL_LOAD_COUNT: 1000
    ports:
      - "8000:8000"
    command: >
      sh -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000'
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
